# Generated by Django 3.0 on 2019-12-17 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='Client',
        ),
    ]
